--PREGUNTA 1 CONOCER EL NUMERO DE EVALUACIONES POR CURSO--
SELECT CURSO.NOMBRECURSO AS CURSO, COUNT(*) AS CANTIDAD_EVALUACIONES FROM TESTAESTUDIANTE
    INNER JOIN CURSO ON TESTAESTUDIANTE.TEST_IDTEST = CURSO.TEST_IDTEST
    GROUP BY CURSO.NOMBRECURSO;

--PREGUNTA 2 CONOCER LOS CURSOS SIN EVALUACIONES--
SELECT NOMBRECURSO, TEST_IDTEST AS EVALUACION FROM CURSO WHERE TEST_IDTEST IS NULL;

--PREGUNTA 3 DETERMINAR LAS EVALUACIONES CON DEFICIENCIA--
--A. SI NO TIENE PREGUNTAS
SELECT TEST.IDTEST,TEST.NOMBRETEST , PREGUNTAS.IDPREGUNTA FROM TEST 
    FULL JOIN PREGUNTAS ON TEST.IDTEST=PREGUNTAS.TEST_IDTEST;

--B. SI HAY PREGUNTAS CON 2 O MENOS ALTERNATIVAS--
SELECT PREGUNTAS_IDPREGUNTAS, COUNT(PREGUNTAS_IDPREGUNTAS) AS CANTIDAD FROM ALTERNATIVAS
    GROUP BY PREGUNTAS_IDPREGUNTAS
    HAVING COUNT(PREGUNTAS_IDPREGUNTAS) <= 2;

--C. SI TODAS LAS ALTERNATIVAS SON CORRECTAS O SI TODAS LAS ALTERNATIVAS SON INCORRECTAS--
SELECT PREGUNTAS_IDPREGUNTAS, PREGUNTAS.ENUNCIADO, ALTERNATIVAS.RESULTADO, COUNT(PREGUNTAS_IDPREGUNTAS) AS CANTIDAD FROM ALTERNATIVAS
    INNER JOIN PREGUNTAS ON PREGUNTAS.IDPREGUNTA = ALTERNATIVAS.PREGUNTAS_IDPREGUNTAS
        GROUP BY PREGUNTAS_IDPREGUNTAS, PREGUNTAS.ENUNCIADO, ALTERNATIVAS.RESULTADO
        HAVING COUNT(RESULTADO) > 2;

--PREGUNTA 4 DETERMINAR CUANTOS ALUMNOS HAY EN CADA CURSO--
SELECT CURSO.NOMBRECURSO, COUNT(*) AS CANTIDAD_DE_ALUMNOS FROM ESTUDIANTE 
    INNER JOIN CURSO ON CURSO.IDCURSO = ESTUDIANTE.CURSO_IDCURSO
    GROUP BY CURSO.NOMBRECURSO;

--PREGUNTA 5 OBTENER EL PUNTAJE NO NORMALIZADO DE CADA EVALUACION--
SELECT PROGRAMA, PUNTAJE_NO_NORMALIZADO FROM TESTAESTUDIANTE
    INNER JOIN TEST ON TEST.IDTEST = TESTAESTUDIANTE.TEST_IDTEST;

--PREGUNTA 6 OBTENER EL PUNTAJE NORMALIZADO--
SELECT ESTUDIANTE.NOMBRE, NOTAS AS NOTA_PRUEBA FROM TESTAESTUDIANTE
    INNER JOIN ESTUDIANTE ON ESTUDIANTE.IDESTUDIANTE = TESTAESTUDIANTE.ESTUDIANTE_IDESTUDIANTE;

--PREGUNTA 7 NOMBRE DE ESTUDIANTES DE UN CURSO DETERMINADO QUE APRUEBEN UNA EVALUACION DETERMINADA (DONDE LA NOTA MINIMA ES 4,0)--
SELECT ESTUDIANTE.NOMBRE AS NOMBRE_ESTUDIANTE, ESTUDIANTE.APELLIDOS AS APELLIDO_ESTUDIANTES, CURSO.NOMBRECURSO,
    TEST.NOMBRETEST, TEST.PROGRAMA, TESTAESTUDIANTE.NOTAS AS NOTA_PRUEBA FROM TESTAESTUDIANTE
        INNER JOIN ESTUDIANTE ON ESTUDIANTE.IDESTUDIANTE = TESTAESTUDIANTE.ESTUDIANTE_IDESTUDIANTE 
        INNER JOIN CURSO ON CURSO.IDCURSO = ESTUDIANTE.CURSO_IDCURSO
        INNER JOIN TEST ON TESTAESTUDIANTE.TEST_IDTEST = CURSO.TEST_IDTEST
            WHERE TESTAESTUDIANTE.NOTAS >= '4,0' AND CURSO.NOMBRECURSO = '4A' AND TEST.IDTEST = '11';
            
--PREGUNTA 8 NOTA PROMEDIO DE LOS ESTUDIANTES DE UN CURSO DETERMINADO, PARA UNA EVALUACION DETERMINADA--
SELECT AVG(NOTAS) FROM TESTAESTUDIANTE;
